# Generated by Django 4.0.5 on 2022-10-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_img', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('small_description', models.TextField()),
                ('full_description', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('language_use', models.CharField(max_length=100)),
                ('project_image', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
