# Generated by Django 4.0.5 on 2022-10-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.TextField()),
                ('full_description', models.TextField()),
                ('sender_phone_no', models.CharField(max_length=100)),
            ],
        ),
    ]
