# Generated by Django 4.1.2 on 2022-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sample_img1',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='sample_img2',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='sample_img3',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
