# Generated by Django 4.1.2 on 2022-11-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_sample_img1_project_sample_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sample_img1',
            field=models.ImageField(upload_to='productimg/sample'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sample_img2',
            field=models.ImageField(upload_to='productimg/sample'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sample_img3',
            field=models.ImageField(upload_to='productimg/sample'),
        ),
    ]
